// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v5.29.3
// source: shared/shared.proto

/* eslint-disable */

export const protobufPackage = "shared";

export interface FilmRef {
  id: string;
  title: string;
  description: string;
  director: string;
  releaseDate: string;
  genre: string[];
  estimation: number;
  backGroundImageKey: string;
  avatarImageKey: string;
  createdAt: string;
  updatedAt: string;
}

export interface ReviewRef {
  id: string;
  userId: string;
  filmId: string;
  title: string;
  description: string;
  rating: number;
  createdAt: string;
  updatedAt: string;
}

export const SHARED_PACKAGE_NAME = "shared";
