// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v5.29.3
// source: common/common.proto

/* eslint-disable */

export const protobufPackage = "common";

export enum SortDirection {
  SORT_DIRECTION_ASC = 0,
  SORT_DIRECTION_DESC = 1,
  UNRECOGNIZED = -1,
}

export interface Empty {
}

export interface PaginationDto {
  page: number;
  limit: number;
}

export interface PaginationMeta {
  totalItems: number;
  page: number;
  limit: number;
  totalPages: number;
  hasNext: boolean;
  hasPrev: boolean;
}

export interface SortingDto {
  field: string;
  direction: SortDirection;
}

export interface FilterDto {
  field: string;
  value: string;
}

export interface FindManyDto {
  pagination: PaginationDto | undefined;
  sorting: SortingDto | undefined;
  filters: FilterDto[];
}

export interface FindOneDocumentDto {
  id: string;
}

export interface SussesResponse {
  susses: boolean;
}

export const COMMON_PACKAGE_NAME = "common";
